### ISSUE TITLE
diff -u causes Guru Meditation 80000003

### ISSUE THREAD

**Issue by jwegne** [hnl/diffutils#1]
Using diff -u fails even with very simple files.

I created two files:
test1:
1
2
4
5

test2:
1
2
3
4
5

Running diff -u test1 test2 caused a Guru after one or two seconds:
Guru Meditation: 80000003
Task 0x3f503200 ('diff')
generated an error of type DSI (Data Storage Interrupt)
on address 0x1f951178
Redzone was damaged
Stackpointer is inside bounds (guard area hit)

The program runs longer if you increase the stack. Running diff without -u (unified) seems to work fine.

AmigaOS 4.1 Final Edition Update 1
WinUAE 3.5.0 64bit
diffutils 54.2

**Comment by hnl** [comment]
Thank you. It was not crashing here a few days ago.
If possible, please send me the crashlog. Will look at the bug this evening.

**Comment by jwegne** [comment]
Please find the crashlog attached. It looks like an infinite loop to me.

[Crashlog_diff_2017-08-26_15-09-04.txt](https://github.com/hnl/diffutils/files/1253680/Crashlog_diff_2017-08-26_15-09-04.txt)

**Comment by hnl** [comment]
thank you :-)

**Comment by hnl** [comment]
Fixed in the new version.
Please test to make sure if it is also working for you now.

**Comment by jwegne** [comment]
Works great!

Thank you for the fast fix. I looked at the change, there were a lot of changes needed to fix this issue. Very much appriciated.

**Comment by hnl** [comment]
Thank you for reporting the problem and retesting it afterwards. The fix itself was not that big, but when fixing the problem, I also included fixes I had made for coreutils.
